sensor:

  default:
    - cust_1_field: ""
    - cust_2_field: ""
    - color: auto
    - color_type: icon
    #- size: 48px
    - lock:
        enabled: false
        duration: 5
        unlock: tap
    - state:
        - value: "on"
          styles:
            card:
              - background-color: var(--button-card-on-background)
              - color: var(--button-card-on-text-color) #'#040404'
            custom_fields:
              corner:
                - color: var(--button-card-corner-on-text-color) #'#6F7075'
              corner_2:
                - color: var(--button-card-corner-on-text-color) #'#6F7075'
              cust_1:
                - color: var(--button-card-cust-1-on-text-color) #'#6F7075'
              cust_2:
                - color: var(--button-card-cust-2-on-text-color) #'#6F7075'

        - value: "unavailable"
          styles:
            icon:
              - color: var(--button-card-disabled-text-color)
            name:
              - color: var(--button-card-disabled-text-color)
            custom_fields:
              cust_1:
                - color: var(--button-card-disabled-text-color)
              cust_2:
                - color: var(--button-card-disabled-text-color)

    # Styles
    - border_radius: var(--button-card-border-radius)
    - background_color: var(--button-card-background-color)
    - icon_color: var(--button-card-icon-color)
    - text_color: var(--button-card-text-color)
    - cust_1_text_color: var(--button-card-cust-1-text-color)
    - cust_2_text_color: var(--button-card-cust-2-text-color)
    - lock_color: var(--button-card-lock-color)


  card:
    type: custom:button-card
    entity: '[[entity]]'
    icon: '[[icon]]'
    name: '[[name]]'
    color: '[[color]]'
    color_type: '[[color_type]]'
    show_last_changed: false
    lock: '[[lock]]'
    size: '[[size]]'
    styles:
      card:
        - padding: 4%
        - font-size: 12px
        - font-weight: bold
        - text-transform: capitalize
        - border-radius: '[[border_radius]]'
        - background-color: '[[background_color]]'
        - color: '[[text_color]]'
      grid:
        - grid-template-areas: '"i n" "i cust_1" "i cust_2"'
        - grid-template-columns: 3fr 5fr
        - grid-template-rows: 1fr 1fr 1fr
      name:
        - font-size: 1.2em #15px
        - align-self: middle
        - justify-self: start
        - padding-top: 0px
        - padding-bottom: 0px
        #- text-transform: lowercase        
      img_cell:
        - justify-content: start
        - align-items: start
        - margin: none
        - height: 100%
        - padding-bottom: 0px
        - padding-right: 0px
        - color: '[[icon_color]]'
      icon:
        - width: 85% # Change to 80% for awesome
        - height: 85% # Change to 80% for awesome
        - margin: none
      lock:
        - color: '[[lock_color]]'
      custom_fields:
        cust_1:
          - padding-bottom: 0px
          - align-self: middle
          - justify-self: start
          - color: "[[cust_1_text_color]]"
          - --icon-color-sensor: "[[cust_1_icon_color]]"
        cust_2:
          - padding-bottom: 0px
          - align-self: middle
          - justify-self: start
          - color: "[[cust_2_text_color]]"
          - --icon-color-sensor: "[[cust_2_icon_color]]"
    custom_fields:
      cust_1: "[[cust_1_field]]"
      cust_2: "[[cust_2_field]]"
    tap_action: '[[tap_action]]'
    hold_action: '[[hold_action]]'
    state: "[[state]]"